### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ninedraft** [praveenpenumaka/numpygo#1]
Hello! Please add a license file to the module root.

[go.dev](https://pkg.go.dev/github.com/praveenpenumaka/numpygo?tab=overview) doesn't show any docs because of legal restrictions. Also it would be lovely if I can use your code in some pet projects ❤️ 

![изображение](https://user-images.githubusercontent.com/12481320/84254410-dab44200-ab19-11ea-9dd9-eecfd16cbb9c.png)

**Comment by praveenpenumaka** [comment]
Added license file. Feel free to use the library.
